dartboard: dartboard.cpp
	g++ -o dartboard dartboard.cpp /usr/lib64/libopencv_core.so.2.4 /usr/lib64/libopencv_highgui.so.2.4 /usr/lib64/libopencv_imgproc.so.2.4 /usr/lib64/libopencv_objdetect.so.2.4
	./dartboard dart15.jpg
